Repository github-community-projects/private-mirrors, pull requests merged in 2024-04, with the labels that each got.

#81 docs: add github issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request-template.md
Labels: documentation

#82 feat: use repo props and rulesets
  app.yml
  package-lock.json
  package.json
  src/bot/graphql.ts
  src/bot/index.ts
  src/pages/orgs/[organizationId]/forks/[forkId].tsx
  src/server/routers/git.ts
  src/server/routers/repos.ts
  test/app.test.ts
  test/fixtures/fork.created.json
  test/fixtures/mirror.created.json
  test/octomock/index.ts
  test/server/git.test.ts
Labels: enhancement

#92 feat: add fallback methods for branch protection and repo description
  package-lock.json
  package.json
  src/bot/graphql.ts
  src/bot/index.ts
  src/bot/rules.ts
  src/pages/orgs/[organizationId]/forks/[forkId].tsx
  src/server/routers/repos.ts
  src/utils/logger.ts
  test/app.test.ts
Labels: enhancement

#99 fix: url in release notes and drop discussions creation
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: fix

#101 feat: release on specific labels
  .github/release-drafter.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: enhancement, feature

#109 fix: cleanup the private mirror if it fails to create
  src/server/routers/git.ts
  test/server/git.test.ts
Labels: fix
