Repository github-community-projects/private-mirrors, pull requests merged in 2024-06, with the labels that each got.

#134 feat: Add Proxy Support
  package-lock.json
  package.json
  scripts/proxy.mjs
  scripts/webhook-relay.mjs
  src/app/api/auth/lib/nextauth-options.ts
  src/utils/proxy.ts
Labels: feature

#154 docs: Clean up wording in usage doc, update screenshots
  docs/images/create-new-mirror.png
  docs/images/public-forks-inside-org.png
  docs/using-the-app.md
Labels: documentation

#162 fix: middleware race condition when checking auth validity
  src/server/git/router.ts
  src/utils/auth.ts
  src/utils/trpc-middleware.ts
  src/utils/trpc-server.ts
Labels: bug, fix

#163 feat: add stricter eslint rules for typescript
  .eslintrc.json
  package-lock.json
  package.json
  src/app/[organizationId]/forks/[forkId]/page.tsx
  src/app/api/auth/[...nextauth]/route.tsx
  src/app/api/auth/lib/nextauth-options.ts
  src/app/api/trpc/trpc-router.ts
  src/app/components/flash/AppNotInstalledFlash.tsx
  src/app/components/header/MainHeader.tsx
  src/app/components/header/WelcomeHeader.tsx
  src/app/context/AuthProvider.tsx
  src/bot/config.ts
  src/bot/index.ts
  src/bot/octokit.ts
  src/hooks/useFork.tsx
  src/hooks/useForks.tsx
  src/hooks/useOrganization.tsx
  src/hooks/useOrganizations.tsx
  src/pages/api/webhooks.ts
  src/utils/auth.ts
  src/utils/logger.ts
Labels: enhancement, feature

#165 chore: Pin actions to SHAs for security and reproducibility
  .github/workflows/auto-labeler.yml
  .github/workflows/build.yml
  .github/workflows/docker-build.yml
  .github/workflows/lint.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: maintenance

#166 feat: update tslog
  src/app/api/auth/lib/nextauth-options.ts
  src/app/context/AuthProvider.tsx
  src/bot/config.ts
  src/bot/rules.ts
  src/server/octokit/controller.ts
  src/server/repos/controller.ts
  src/utils/logger.ts
Labels: feature

#168 fix: stringify json logging to be single line
  package-lock.json
  package.json
  src/utils/logger.ts
Labels: bug, fix

#173 chore: local dev fixes
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: maintenance

#171 fix: Enforce repository name length limit in dialogs
  src/app/components/dialog/CreateMirrorDialog.tsx
  src/app/components/dialog/EditMirrorDialog.tsx
  src/server/repos/schema.ts
  test/server/repos.test.ts
Labels: fix

#178 fix: edit mirror dialog to display current mirror name
  src/app/components/dialog/EditMirrorDialog.tsx
Labels: fix

#180 chore: pin shas in Dockerfile
  Dockerfile
Labels: maintenance

#177 fix: pagination issues
  src/app/[organizationId]/forks/[forkId]/page.tsx
  src/app/[organizationId]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: bug, fix

#181 fix: use private org for location when set
  src/app/[organizationId]/forks/[forkId]/page.tsx
  src/app/api/trpc/trpc-router.ts
  src/app/components/dialog/DeleteMirrorDialog.tsx
  src/server/config/controller.ts
  src/server/config/router.ts
  src/server/config/schema.ts
  test/server/config.test.ts
Labels: bug, fix

#179 feat: add error messages to error flashes
  src/app/[organizationId]/forks/[forkId]/page.tsx
  src/app/components/flash/SuccessFlash.tsx
  src/server/repos/controller.ts
  src/server/repos/schema.ts
Labels: enhancement, feature

#187 fix: improve hooks to show loading/error table
  src/app/[organizationId]/forks/[forkId]/page.tsx
  src/app/[organizationId]/page.tsx
  src/app/page.tsx
  src/hooks/useFork.tsx
  src/hooks/useForks.tsx
  src/hooks/useOrganization.tsx
Labels: bug, fix

#193 fix: add catch handling for already exists
  src/server/repos/controller.ts
Labels: bug, fix
