Repository github-community-projects/private-mirrors, pull requests merged in 2024-07, with the labels that each got.

#198 fix: add proxy import to webhook entrypoint
  src/bot/index.ts
Labels: fix

#199 docs: Rename docs and string references from ICF to PMA
  .github/ISSUE_TEMPLATE/config.yml
  .github/release-drafter.yml
  CONTRIBUTING.md
  README.md
  SUPPORT.md
  app.yml
  docs/using-the-app.md
Labels: documentation

#203 docs: Update README.md with new screenshot
  README.md
Labels: documentation

#202 fix: add min level to logger
  .env.example
  env.mjs
  src/app/api/auth/lib/nextauth-options.ts
  src/server/repos/controller.ts
  src/utils/logger.ts
Labels: bug, fix

#204 feat: rename icf to pma in code
  .github/workflows/docker-build.yml
  package-lock.json
  package.json
  src/app/components/header/MainHeader.tsx
  src/app/components/header/WelcomeHeader.tsx
  src/app/components/login/Login.tsx
  src/bot/config.ts
  src/bot/rules.ts
  src/server/git/controller.ts
  src/server/repos/controller.ts
  test/app.test.ts
  test/config.test.ts
  test/fixtures/mirror.created.json
Labels: enhancement, feature

#209 docs: Update one more screenshot to change ICF->PMA
  README.md
Labels: documentation

#217 docs: Update youtube link to final video
  README.md
Labels: documentation
