Repository github-community-projects/private-mirrors, pull requests merged in 2024-05, with the labels that each got.

#124 feat: swap out smee with homegrown proxy client
  .env.example
  README.md
  env.mjs
  package-lock.json
  package.json
  scripts/probot-forwarder.js
  scripts/webhook-relay.mjs
Labels: enhancement, feature

#131 fix: Disable Global Git Hooks in Simple Git
  src/server/routers/git.ts
Labels: fix

#144 ci: release when a new feature hits main
  .github/workflows/release.yml
Labels: automation

#145 chore: remove pull_request target if we already have pull_request_target
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
  README.md
Labels: maintenance

#147 chore: change from only security updates to grouping
  .github/dependabot.yml
Labels: maintenance

#151 feat: refresh access token on expiration
  src/app/api/auth/lib/nextauth-options.ts
  src/app/context/AuthProvider.tsx
  src/app/layout.tsx
  src/types/next-auth.d.ts
Labels: bug, enhancement, feature
