Repository github-community-projects/private-mirrors, pull requests merged in 2025-03, with the labels that each got.

#321 fix: simplify syncRepos call in push to resolve trpc issue
  src/bot/index.ts
Labels: fix, release

#325 fix(ci): only run actions jobs on push to main
  .github/workflows/build.yml
  .github/workflows/docker-build.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: maintenance, fix, github_actions

#330 fix(deps): update and override vulnerable dependencies
  package-lock.json
  package.json
Labels: bug, fix, release

#344 chore: specify supported lts node.js versions
  docs/developing.md
  package-lock.json
  package.json
Labels: maintenance

#345 chore: support node.js version managers
  .nvmrc
  docs/developing.md
Labels: maintenance

#346 fix(deps): update next to 14.2.25
  package-lock.json
  package.json
Labels: bug, dependencies, fix, vuln, release

#341 chore: remove the deprecated husky setup
  .husky/pre-commit
  package-lock.json
  package.json
Labels: maintenance

#350 ci: use setup-node action
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/tests.yml
Labels: maintenance, automation, github_actions

#351 ci: use docker actions
  .github/workflows/docker-build.yml
  Dockerfile
Labels: maintenance, automation, docker
